import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

export const metadata = {
  title: "The Everyday Journal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" 
      crossOrigin="anonymous" referrerPolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
    <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet" />
      </head>
      <body>
      <AuthProvider>
        <div className = 'flex flex-col min-h-screen relative bg-slate-900 text-gray-200'>
          <main >
              {children}
          </main>
        </div>
        </AuthProvider>
      </body>

    </html>
  );
}
